#!/usr/bin/env python3
"""Regenerate data/qa.jsonl (304 factual questions, seeded)."""
import json, random, pathlib

random.seed(20260812)
qa = []
def add(q, *answers):
    qa.append({"question": q, "answers": [a.lower() for a in answers]})

caps = [("France","Paris"),("Japan","Tokyo"),("Italy","Rome"),("Spain","Madrid"),
 ("Germany","Berlin"),("Russia","Moscow"),("China","Beijing"),("Egypt","Cairo"),
 ("Canada","Ottawa"),("Australia","Canberra"),("Brazil","Brasilia","Brasília"),
 ("India","New Delhi","Delhi"),("Turkey","Ankara"),("Greece","Athens"),
 ("Portugal","Lisbon"),("Netherlands","Amsterdam"),("Sweden","Stockholm"),
 ("Norway","Oslo"),("Finland","Helsinki"),("Poland","Warsaw"),
 ("Austria","Vienna"),("Switzerland","Bern"),("Belgium","Brussels"),
 ("Ireland","Dublin"),("Denmark","Copenhagen"),("South Korea","Seoul"),
 ("Thailand","Bangkok"),("Vietnam","Hanoi"),("Indonesia","Jakarta"),
 ("Malaysia","Kuala Lumpur"),("Philippines","Manila"),("Mexico","Mexico City"),
 ("Argentina","Buenos Aires"),("Chile","Santiago"),("Peru","Lima"),
 ("Colombia","Bogota","Bogotá"),("Kenya","Nairobi"),("Nigeria","Abuja"),
 ("South Africa","Pretoria","Cape Town"),("Morocco","Rabat"),
 ("Saudi Arabia","Riyadh"),("United Arab Emirates","Abu Dhabi"),
 ("Jordan","Amman"),("Iraq","Baghdad"),("Lebanon","Beirut"),
 ("Kuwait","Kuwait City"),("Qatar","Doha"),("Oman","Muscat"),
 ("New Zealand","Wellington"),("Iceland","Reykjavik","Reykjavík")]
for country, *ans in caps:
    add(f"What is the capital of {country}?", *ans)

books = [("Romeo and Juliet","Shakespeare","William Shakespeare"),
 ("Hamlet","Shakespeare","William Shakespeare"),("Pride and Prejudice","Jane Austen","Austen"),
 ("1984","George Orwell","Orwell"),("Animal Farm","George Orwell","Orwell"),
 ("The Old Man and the Sea","Hemingway","Ernest Hemingway"),("War and Peace","Tolstoy","Leo Tolstoy"),
 ("Anna Karenina","Tolstoy","Leo Tolstoy"),("Crime and Punishment","Dostoevsky","Fyodor Dostoevsky"),
 ("The Great Gatsby","Fitzgerald","F. Scott Fitzgerald"),("Moby-Dick","Melville","Herman Melville"),
 ("Don Quixote","Cervantes","Miguel de Cervantes"),("The Odyssey","Homer"),("The Iliad","Homer"),
 ("Harry Potter and the Philosopher's Stone","J.K. Rowling","Rowling"),("The Hobbit","Tolkien","J.R.R. Tolkien"),
 ("The Lord of the Rings","Tolkien","J.R.R. Tolkien"),("A Tale of Two Cities","Dickens","Charles Dickens"),
 ("Oliver Twist","Dickens","Charles Dickens"),("Great Expectations","Dickens","Charles Dickens"),
 ("Jane Eyre","Charlotte Bronte","Charlotte Brontë","Bronte"),
 ("Wuthering Heights","Emily Bronte","Emily Brontë","Bronte"),
 ("The Adventures of Huckleberry Finn","Mark Twain","Twain"),
 ("The Adventures of Tom Sawyer","Mark Twain","Twain"),("Frankenstein","Mary Shelley","Shelley"),
 ("Dracula","Bram Stoker","Stoker"),("The Picture of Dorian Gray","Oscar Wilde","Wilde"),
 ("One Hundred Years of Solitude","Gabriel Garcia Marquez","García Márquez","Marquez"),
 ("The Alchemist","Paulo Coelho","Coelho"),("Things Fall Apart","Chinua Achebe","Achebe")]
for title, *ans in books:
    add(f"Who wrote {title}?", *ans)

sci = [("What is the chemical symbol for gold?","Au"),("What is the chemical symbol for silver?","Ag"),
 ("What is the chemical symbol for iron?","Fe"),("What is the chemical symbol for sodium?","Na"),
 ("What is the chemical symbol for potassium?","K"),("What is the chemical symbol for oxygen?","O"),
 ("What planet is known as the Red Planet?","Mars"),("What is the largest planet in our solar system?","Jupiter"),
 ("What is the smallest planet in our solar system?","Mercury"),("What is the closest planet to the Sun?","Mercury"),
 ("How many planets are in our solar system?","eight","8"),
 ("What gas do plants absorb from the atmosphere?","carbon dioxide","CO2"),
 ("What gas do plants release during photosynthesis?","oxygen"),
 ("What is the powerhouse of the cell?","mitochondria","mitochondrion"),
 ("What is the speed of light in a vacuum, approximately?","300,000","3x10^8","299,792"),
 ("Who developed the theory of general relativity?","Einstein","Albert Einstein"),
 ("Who formulated the laws of motion and universal gravitation?","Newton","Isaac Newton"),
 ("Who is known as the father of evolution?","Darwin","Charles Darwin"),
 ("What is the hardest natural substance on Earth?","diamond"),
 ("What is the most abundant gas in Earth's atmosphere?","nitrogen"),
 ("What is the chemical formula for water?","H2O"),
 ("What is the chemical formula for table salt?","NaCl","sodium chloride"),
 ("How many bones are in the adult human body?","206"),("What organ pumps blood through the body?","heart"),
 ("What is the largest organ of the human body?","skin"),
 ("What blood cells fight infection?","white","white blood cells","leukocytes"),
 ("At what temperature does water boil at sea level in Celsius?","100"),
 ("At what temperature does water freeze in Celsius?","0","zero"),
 ("What force keeps us on the ground?","gravity"),("What is the center of an atom called?","nucleus"),
 ("What particle has a negative charge?","electron"),("What particle has a positive charge?","proton"),
 ("What is the study of living organisms called?","biology"),("What is the study of weather called?","meteorology"),
 ("What natural satellite orbits the Earth?","the Moon","moon"),
 ("How long does Earth take to orbit the Sun?","365","one year","a year"),
 ("What is the largest mammal on Earth?","blue whale"),("What is the fastest land animal?","cheetah"),
 ("What do bees collect from flowers?","nectar","pollen"),("What metal is liquid at room temperature?","mercury"),
 ("What is the unit of electrical resistance?","ohm"),("What is the unit of electrical current?","ampere","amp"),
 ("What is the unit of frequency?","hertz","Hz"),("What is the unit of force?","newton"),
 ("What is the unit of energy in the SI system?","joule"),("What is the square root of 144?","12","twelve"),
 ("What is 15 percent of 200?","30","thirty"),("How many degrees are in a right angle?","90","ninety"),
 ("How many sides does a hexagon have?","6","six"),("What is the value of pi to two decimal places?","3.14")]
for q, *ans in sci:
    add(q, *ans)

hist = [("In what year did World War II end?","1945"),("In what year did World War I begin?","1914"),
 ("In what year did the Titanic sink?","1912"),
 ("Who was the first President of the United States?","George Washington","Washington"),
 ("Who was the first person to walk on the Moon?","Neil Armstrong","Armstrong"),
 ("In what year did humans first land on the Moon?","1969"),
 ("What ancient civilization built the pyramids of Giza?","Egyptian","Egyptians","ancient Egypt"),
 ("What wall divided Berlin during the Cold War?","Berlin Wall"),
 ("In what year did the Berlin Wall fall?","1989"),
 ("Who painted the Mona Lisa?","Leonardo da Vinci","da Vinci","Leonardo"),
 ("Who painted the Sistine Chapel ceiling?","Michelangelo"),("Who painted Starry Night?","Van Gogh","Vincent van Gogh"),
 ("What is the longest river in the world?","Nile","Amazon"),("What is the largest ocean on Earth?","Pacific"),
 ("What is the smallest ocean?","Arctic"),
 ("What is the largest desert in the world?","Sahara","Antarctic","Antarctica"),
 ("What is the tallest mountain in the world?","Everest","Mount Everest"),
 ("What is the largest country by area?","Russia"),
 ("What is the most populous country in the world?","India","China"),
 ("What is the smallest country in the world?","Vatican","Vatican City"),
 ("On what continent is the Sahara Desert located?","Africa"),
 ("What continent is Brazil located on?","South America"),("What continent is Egypt located in?","Africa"),
 ("What is the longest wall in the world?","Great Wall","Great Wall of China"),
 ("What canal connects the Atlantic and Pacific oceans?","Panama","Panama Canal"),
 ("What canal connects the Mediterranean and Red seas?","Suez","Suez Canal"),
 ("What is the largest island in the world?","Greenland"),("What sea separates Europe and Africa?","Mediterranean"),
 ("What strait separates Asia and North America?","Bering","Bering Strait"),
 ("What mountain range separates Europe and Asia?","Ural","Urals")]
for q, *ans in hist:
    add(q, *ans)

misc = [("How many players are on a soccer team on the field?","11","eleven"),
 ("How many players are on a basketball team on the court?","5","five"),
 ("How often are the Summer Olympic Games held?","four","every four years","4"),
 ("In what country did the Olympic Games originate?","Greece"),("What sport is known as the beautiful game?","soccer","football"),
 ("How many rings are on the Olympic flag?","5","five"),("What country hosted the 2022 FIFA World Cup?","Qatar"),
 ("How many strings does a standard guitar have?","6","six"),("How many keys does a standard piano have?","88"),
 ("Who composed the Ninth Symphony with the Ode to Joy?","Beethoven","Ludwig van Beethoven"),
 ("How many days are in a leap year?","366"),("How many hours are in a day?","24","twenty-four"),
 ("How many minutes are in an hour?","60","sixty"),("How many continents are there?","7","seven"),
 ("How many colors are in a rainbow?","7","seven"),("What is the currency of Japan?","yen"),
 ("What is the currency of the United Kingdom?","pound","pound sterling"),
 ("What is the currency of Saudi Arabia?","riyal"),
 ("What is the currency used in most of the European Union?","euro"),
 ("What language is spoken in Brazil?","Portuguese"),
 ("What language has the most native speakers in the world?","Mandarin","Chinese"),
 ("What is the tallest building in the world?","Burj Khalifa"),
 ("In what city is the Eiffel Tower located?","Paris"),("In what city is the Statue of Liberty located?","New York"),
 ("In what city is the Colosseum located?","Rome"),("In what country is the Taj Mahal located?","India"),
 ("In what country is Machu Picchu located?","Peru"),("What is the national animal of China?","panda","giant panda"),
 ("What is the largest bird in the world?","ostrich"),("What is the king of the jungle?","lion")]
for q, *ans in misc:
    add(q, *ans)

extra = [("What is the chemical symbol for carbon?","C"),("What is the chemical symbol for hydrogen?","H"),
 ("What is the chemical symbol for helium?","He"),("What is the chemical symbol for nitrogen?","N"),
 ("What is the chemical symbol for calcium?","Ca"),("What is the chemical symbol for copper?","Cu"),
 ("What is the chemical symbol for zinc?","Zn"),("What is the chemical symbol for lead?","Pb"),
 ("What is the chemical symbol for tin?","Sn"),("What is the chemical symbol for chlorine?","Cl"),
 ("What is the chemical symbol for helium named after?","the sun","Helios"),
 ("What is the atomic number of hydrogen?","1","one"),("What is the atomic number of oxygen?","8","eight"),
 ("What number of protons does carbon have?","6","six"),("What is the freezing point of water in Fahrenheit?","32"),
 ("What is the boiling point of water in Fahrenheit?","212"),("What planet has the most moons?","Saturn","Jupiter"),
 ("What is the ringed planet?","Saturn"),("What galaxy do we live in?","Milky Way"),
 ("What is the nearest star to Earth?","the Sun","Sun"),("What is the study of stars and space called?","astronomy"),
 ("What is the study of earthquakes called?","seismology"),("What is the study of insects called?","entomology"),
 ("What is the study of ancient life through fossils called?","paleontology"),
 ("What instrument measures atmospheric pressure?","barometer"),("What instrument measures earthquakes?","seismograph"),
 ("What instrument measures temperature?","thermometer"),
 ("What is the process by which plants make food called?","photosynthesis"),
 ("What is the largest artery in the human body?","aorta"),("How many chambers does the human heart have?","4","four"),
 ("What is the tallest animal in the world?","giraffe"),("What is the largest fish in the world?","whale shark"),
 ("What is the fastest bird in the world?","peregrine falcon"),
 ("What animal is known for changing its skin color?","chameleon"),("What is a group of lions called?","pride"),
 ("What is a group of wolves called?","pack"),("What is a baby kangaroo called?","joey"),
 ("What is a baby cat called?","kitten"),("What is a baby dog called?","puppy"),("What is a baby cow called?","calf"),
 ("Who invented the telephone?","Alexander Graham Bell","Bell"),("Who invented the light bulb?","Thomas Edison","Edison"),
 ("Who invented the printing press?","Gutenberg","Johannes Gutenberg"),
 ("Who discovered penicillin?","Alexander Fleming","Fleming"),
 ("Who discovered gravity, according to legend, from an apple?","Newton","Isaac Newton"),
 ("Who was the wife of King Henry VIII who was beheaded?","Anne Boleyn"),
 ("Who was the queen of ancient Egypt famous for her beauty?","Cleopatra"),
 ("Who was the first female Prime Minister of the United Kingdom?","Margaret Thatcher","Thatcher"),
 ("Who was the leader of the Soviet Union during WWII?","Stalin","Joseph Stalin"),
 ("Who was the president of the US during the Civil War?","Lincoln","Abraham Lincoln"),
 ("Who assassinated Abraham Lincoln?","John Wilkes Booth","Booth"),
 ("Who was the first man in space?","Yuri Gagarin","Gagarin"),
 ("Who was the first woman in space?","Valentina Tereshkova","Tereshkova"),
 ("What ship famously sank in 1912?","Titanic"),
 ("What was the name of Christopher Columbus's ship?","Santa Maria","Santa María"),
 ("Who discovered America in 1492, according to tradition?","Columbus","Christopher Columbus"),
 ("What empire was ruled by Julius Caesar?","Roman","Roman Empire","Rome"),
 ("Who was Julius Caesar's adopted heir?","Augustus","Octavian"),
 ("What was the ancient Greek city-state famous for warriors?","Sparta"),
 ("What was the ancient Greek city-state famous for philosophy?","Athens"),
 ("What is the name of the Norse god of thunder?","Thor"),("What is the name of the Greek god of the sea?","Poseidon"),
 ("What is the name of the Roman god of war?","Mars"),("What is the name of the Egyptian god of the sun?","Ra"),
 ("What river flows through Egypt?","Nile"),("What river flows through Paris?","Seine"),
 ("What river flows through London?","Thames"),("What mountain range runs through South America?","Andes"),
 ("What mountain range is home to Mount Everest?","Himalayas"),
 ("What is the capital of the United States?","Washington","Washington D.C.","Washington DC"),
 ("What is the largest city in the United States?","New York","New York City"),
 ("What is the largest city in Japan?","Tokyo"),("What is the most populous city in the world?","Tokyo"),
 ("What US state is known as the Sunshine State?","Florida"),("What US state is known as the Golden State?","California"),
 ("What is the largest state in the US by area?","Alaska"),("What is the smallest state in the US by area?","Rhode Island"),
 ("How many states are in the United States?","50","fifty"),
 ("How many countries are in the European Union?","27","twenty-seven"),
 ("What organization is headquartered in New York and promotes world peace?","United Nations","UN"),
 ("What is NATO short for?","North Atlantic Treaty Organization"),
 ("What year did the French Revolution begin?","1789"),
 ("What year did the American Declaration of Independence get signed?","1776"),
 ("What document begins with 'We the People'?","the Constitution","US Constitution"),
 ("What war was fought between the North and South in the US?","Civil War","American Civil War"),
 ("What was the name of the airplane that dropped the first atomic bomb?","Enola Gay"),
 ("In what city was John F. Kennedy assassinated?","Dallas"),
 ("Who wrote the theory of relativity's famous equation E=mc2?","Einstein","Albert Einstein"),
 ("What company was founded by Steve Jobs and Steve Wozniak?","Apple"),
 ("What company was founded by Bill Gates?","Microsoft"),("What company was founded by Jeff Bezos?","Amazon"),
 ("What social media platform was founded by Mark Zuckerberg?","Facebook"),
 ("Who is the founder of Tesla and SpaceX?","Elon Musk","Musk"),("What is the world's largest search engine?","Google"),
 ("What programming language is named after a snake?","Python"),("What does CPU stand for?","central processing unit"),
 ("What does HTML stand for?","hypertext markup language"),("What does WWW stand for?","world wide web"),
 ("What does GPS stand for?","global positioning system"),("What year was the first iPhone released?","2007"),
 ("What company created the Windows operating system?","Microsoft"),
 ("What company created the Android operating system?","Google"),
 ("What is the best-selling video game console of all time?","PlayStation 2","PS2"),
 ("What was the first man-made satellite launched into space?","Sputnik"),("What year was Sputnik launched?","1957"),
 ("What space agency put the first man on the moon?","NASA"),
 ("What is the name of NASA's most famous space telescope?","Hubble"),
 ("How many teeth does an adult human typically have?","32","thirty-two"),
 ("What is the largest muscle in the human body?","gluteus maximus"),
 ("What vitamin do you get primarily from sunlight?","vitamin D"),
 ("What part of the plant conducts photosynthesis?","leaves","leaf"),
 ("What do you call a doctor who treats teeth?","dentist"),
 ("What do you call a doctor who treats animals?","veterinarian","vet"),
 ("What do you call a doctor who treats the heart?","cardiologist")]
for q, *ans in extra:
    add(q, *ans)

random.shuffle(qa)
out = pathlib.Path(__file__).parent.parent.parent / "data" / "qa.jsonl"
out.parent.mkdir(exist_ok=True)
with open(out, "w") as f:
    for i, ex in enumerate(qa):
        ex["id"] = f"qa_{i:04d}"
        f.write(json.dumps(ex) + "\n")
print(f"wrote {len(qa)} questions to {out}")
