#!/usr/bin/env python3
"""Build data/qa_v2.jsonl: ~1000 questions, ~40% factual (single-answer,
match_mode="any") and ~60% explain/why (multi-concept, match_mode="all").

Design note on why the mix isn't drawn from a literature benchmark: factoid
QA (NQ-open, TriviaQA, SQuAD) and non-factoid/explanatory QA (ANTIQUE,
WikiQA) are studied as separate benchmark categories in the literature,
not combined with an established ratio. The 60/40 explain-weighted split
here is a deliberate choice for THIS project's purpose: E1 (v1) showed
that "unsafe" (mid-answer) stopping boundaries are concentrated in
longer, elaborative answers, and explain/why questions are what reliably
produce those, so the dataset is weighted toward the question type that
actually exercises the phenomenon under study.

Each entry:
  id, question, type ("factual" | "explain"),
  answers (list of lowercase required strings),
  match_mode ("any" | "all")
"any": correct if the text contains at least one of `answers` (factual).
"all": correct if the text contains every one of `answers` (explain --
       each string is a short required concept/keyword).
"""
import json, random, itertools, pathlib

random.seed(20260826)
qa = []

def add_factual(q, *answers):
    qa.append({"question": q, "answers": [a.lower() for a in answers],
               "match_mode": "any", "type": "factual"})

def add_explain(q, *concepts):
    qa.append({"question": q, "answers": [c.lower() for c in concepts],
               "match_mode": "all", "type": "explain"})

# =====================================================================
# FACTUAL (~40%, target ~400) -- reuse + expand the v1 categories
# =====================================================================
caps = [("France","Paris"),("Japan","Tokyo"),("Italy","Rome"),("Spain","Madrid"),
 ("Germany","Berlin"),("Russia","Moscow"),("China","Beijing"),("Egypt","Cairo"),
 ("Canada","Ottawa"),("Australia","Canberra"),("Brazil","Brasilia","Brasília"),
 ("India","New Delhi","Delhi"),("Turkey","Ankara"),("Greece","Athens"),
 ("Portugal","Lisbon"),("Netherlands","Amsterdam"),("Sweden","Stockholm"),
 ("Norway","Oslo"),("Finland","Helsinki"),("Poland","Warsaw"),
 ("Austria","Vienna"),("Switzerland","Bern"),("Belgium","Brussels"),
 ("Ireland","Dublin"),("Denmark","Copenhagen"),("South Korea","Seoul"),
 ("Thailand","Bangkok"),("Vietnam","Hanoi"),("Indonesia","Jakarta"),
 ("Malaysia","Kuala Lumpur"),("Philippines","Manila"),("Mexico","Mexico City"),
 ("Argentina","Buenos Aires"),("Chile","Santiago"),("Peru","Lima"),
 ("Colombia","Bogota","Bogotá"),("Kenya","Nairobi"),("Nigeria","Abuja"),
 ("South Africa","Pretoria","Cape Town"),("Morocco","Rabat"),
 ("Saudi Arabia","Riyadh"),("United Arab Emirates","Abu Dhabi"),
 ("Jordan","Amman"),("Iraq","Baghdad"),("Lebanon","Beirut"),
 ("Kuwait","Kuwait City"),("Qatar","Doha"),("Oman","Muscat"),
 ("New Zealand","Wellington"),("Iceland","Reykjavik","Reykjavík"),
 ("Ukraine","Kyiv"),("Hungary","Budapest"),("Czech Republic","Prague"),
 ("Romania","Bucharest"),("Bulgaria","Sofia"),("Croatia","Zagreb"),
 ("Serbia","Belgrade"),("Israel","Jerusalem"),("Pakistan","Islamabad"),
 ("Bangladesh","Dhaka"),("Sri Lanka","Colombo"),("Nepal","Kathmandu"),
 ("Myanmar","Naypyidaw"),("Cuba","Havana"),("Venezuela","Caracas"),
 ("Ecuador","Quito"),("Bolivia","La Paz","Sucre"),("Uruguay","Montevideo"),
 ("Paraguay","Asuncion","Asunción"),("Ethiopia","Addis Ababa"),
 ("Ghana","Accra"),("Tanzania","Dodoma"),("Uganda","Kampala"),
 ("Zimbabwe","Harare"),("Algeria","Algiers"),("Tunisia","Tunis"),
 ("Libya","Tripoli"),("Sudan","Khartoum"),("Syria","Damascus"),
 ("Yemen","Sanaa"),("Afghanistan","Kabul"),("Mongolia","Ulaanbaatar"),
 ("Kazakhstan","Astana"),("Uzbekistan","Tashkent"),]
for country, *ans in caps:
    add_factual(f"What is the capital of {country}?", *ans)
    add_factual(f"What city is the capital of {country}?", *ans)
    add_factual(f"Do you know the capital city of {country}?", *ans)

books = [("Romeo and Juliet","Shakespeare"),("Hamlet","Shakespeare"),
 ("Pride and Prejudice","Jane Austen","Austen"),("1984","George Orwell","Orwell"),
 ("Animal Farm","George Orwell","Orwell"),("The Old Man and the Sea","Hemingway"),
 ("War and Peace","Tolstoy"),("Anna Karenina","Tolstoy"),
 ("Crime and Punishment","Dostoevsky"),("The Great Gatsby","Fitzgerald"),
 ("Moby-Dick","Melville"),("Don Quixote","Cervantes"),("The Odyssey","Homer"),
 ("The Iliad","Homer"),("The Hobbit","Tolkien"),("A Tale of Two Cities","Dickens"),
 ("Oliver Twist","Dickens"),("Great Expectations","Dickens"),
 ("Jane Eyre","Charlotte Bronte","Bronte"),("Wuthering Heights","Emily Bronte","Bronte"),
 ("Frankenstein","Mary Shelley","Shelley"),("Dracula","Bram Stoker","Stoker"),
 ("The Picture of Dorian Gray","Oscar Wilde","Wilde"),
 ("One Hundred Years of Solitude","Gabriel Garcia Marquez","Marquez"),
 ("The Alchemist","Paulo Coelho","Coelho"),("Things Fall Apart","Chinua Achebe","Achebe"),
 ("Brave New World","Aldous Huxley","Huxley"),("Fahrenheit 451","Ray Bradbury","Bradbury"),
 ("The Catcher in the Rye","J.D. Salinger","Salinger"),
 ("To Kill a Mockingbird","Harper Lee"),("Ulysses","James Joyce","Joyce"),]
for title, *ans in books:
    add_factual(f"Who wrote {title}?", *ans)

sci = [("What is the chemical symbol for gold?","Au"),("What is the chemical symbol for silver?","Ag"),
 ("What is the chemical symbol for iron?","Fe"),("What is the chemical symbol for sodium?","Na"),
 ("What planet is known as the Red Planet?","Mars"),("What is the largest planet in our solar system?","Jupiter"),
 ("What is the smallest planet in our solar system?","Mercury"),
 ("How many planets are in our solar system?","eight","8"),
 ("What is the powerhouse of the cell?","mitochondria"),
 ("Who developed the theory of general relativity?","Einstein"),
 ("Who formulated the laws of motion and universal gravitation?","Newton"),
 ("What is the hardest natural substance on Earth?","diamond"),
 ("What is the chemical formula for water?","H2O"),
 ("How many bones are in the adult human body?","206"),
 ("What organ pumps blood through the body?","heart"),
 ("What is the largest organ of the human body?","skin"),
 ("At what temperature does water boil at sea level in Celsius?","100"),
 ("At what temperature does water freeze in Celsius?","0"),
 ("What is the center of an atom called?","nucleus"),
 ("What particle has a negative charge?","electron"),
 ("What is the study of living organisms called?","biology"),
 ("What natural satellite orbits the Earth?","the Moon","moon"),
 ("What is the largest mammal on Earth?","blue whale"),
 ("What is the fastest land animal?","cheetah"),
 ("What metal is liquid at room temperature?","mercury"),
 ("What is the unit of electrical resistance?","ohm"),
 ("What is the square root of 144?","12"),
 ("How many sides does a hexagon have?","6","six"),
 ("What galaxy do we live in?","Milky Way"),
 ("What is the nearest star to Earth?","the Sun","Sun"),
 ("How many chambers does the human heart have?","4","four"),]
for q, *ans in sci:
    add_factual(q, *ans)

hist = [("In what year did World War II end?","1945"),("In what year did World War I begin?","1914"),
 ("Who was the first President of the United States?","George Washington","Washington"),
 ("Who was the first person to walk on the Moon?","Neil Armstrong","Armstrong"),
 ("In what year did humans first land on the Moon?","1969"),
 ("Who painted the Mona Lisa?","Leonardo da Vinci","da Vinci"),
 ("Who painted the Sistine Chapel ceiling?","Michelangelo"),
 ("What is the longest river in the world?","Nile","Amazon"),
 ("What is the largest ocean on Earth?","Pacific"),
 ("What is the largest desert in the world?","Sahara"),
 ("What is the tallest mountain in the world?","Everest"),
 ("What is the largest country by area?","Russia"),
 ("What is the smallest country in the world?","Vatican"),
 ("What is the currency of Japan?","yen"),
 ("What is the currency of Saudi Arabia?","riyal"),
 ("What language is spoken in Brazil?","Portuguese"),
 ("In what city is the Eiffel Tower located?","Paris"),
 ("In what country is the Taj Mahal located?","India"),]
for q, *ans in hist:
    add_factual(q, *ans)

extra_facts = [
 ("How many players are on a soccer team on the field?","11","eleven"),
 ("How many players are on a basketball team on the court?","5","five"),
 ("How often are the Summer Olympic Games held?","four","every four years","4"),
 ("What sport is known as the beautiful game?","soccer","football"),
 ("How many rings are on the Olympic flag?","5","five"),
 ("How many strings does a standard guitar have?","6","six"),
 ("How many keys does a standard piano have?","88"),
 ("How many days are in a leap year?","366"),
 ("How many hours are in a day?","24","twenty-four"),
 ("How many minutes are in an hour?","60","sixty"),
 ("How many continents are there?","7","seven"),
 ("How many colors are in a rainbow?","7","seven"),
 ("What is the currency used in most of the European Union?","euro"),
 ("What language has the most native speakers in the world?","Mandarin","Chinese"),
 ("What is the tallest building in the world?","Burj Khalifa"),
 ("What is the national animal of China?","panda","giant panda"),
 ("What is the largest bird in the world?","ostrich"),
 ("What is the king of the jungle?","lion"),
 ("What is the chemical symbol for carbon?","C"),
 ("What is the chemical symbol for hydrogen?","H"),
 ("What is the chemical symbol for helium?","He"),
 ("What is the chemical symbol for nitrogen?","N"),
 ("What is the chemical symbol for calcium?","Ca"),
 ("What is the chemical symbol for copper?","Cu"),
 ("What is the atomic number of hydrogen?","1","one"),
 ("What is the atomic number of oxygen?","8","eight"),
 ("What is the freezing point of water in Fahrenheit?","32"),
 ("What is the boiling point of water in Fahrenheit?","212"),
 ("What planet has the most moons?","Saturn","Jupiter"),
 ("What is the ringed planet?","Saturn"),
 ("What is the study of stars and space called?","astronomy"),
 ("What is the study of earthquakes called?","seismology"),
 ("What is the study of insects called?","entomology"),
 ("What instrument measures atmospheric pressure?","barometer"),
 ("What instrument measures earthquakes?","seismograph"),
 ("What instrument measures temperature?","thermometer"),
 ("What is the largest artery in the human body?","aorta"),
 ("What is the tallest animal in the world?","giraffe"),
 ("What is the largest fish in the world?","whale shark"),
 ("What is the fastest bird in the world?","peregrine falcon"),
 ("What animal is known for changing its skin color?","chameleon"),
 ("What is a group of lions called?","pride"),
 ("What is a group of wolves called?","pack"),
 ("What is a baby kangaroo called?","joey"),
 ("Who invented the telephone?","Alexander Graham Bell","Bell"),
 ("Who invented the light bulb?","Thomas Edison","Edison"),
 ("Who invented the printing press?","Gutenberg"),
 ("Who discovered penicillin?","Alexander Fleming","Fleming"),
 ("Who was the queen of ancient Egypt famous for her beauty?","Cleopatra"),
 ("Who was the first female Prime Minister of the United Kingdom?","Margaret Thatcher","Thatcher"),
 ("Who was the president of the US during the Civil War?","Lincoln","Abraham Lincoln"),
 ("Who was the first man in space?","Yuri Gagarin","Gagarin"),
 ("What ship famously sank in 1912?","Titanic"),
 ("What empire was ruled by Julius Caesar?","Roman","Roman Empire","Rome"),
 ("What river flows through Egypt?","Nile"),
 ("What river flows through Paris?","Seine"),
 ("What river flows through London?","Thames"),
 ("What mountain range runs through South America?","Andes"),
 ("What mountain range is home to Mount Everest?","Himalayas"),
 ("What is the capital of the United States?","Washington","Washington D.C."),
 ("What is the largest city in the United States?","New York","New York City"),
 ("What US state is known as the Sunshine State?","Florida"),
 ("What US state is known as the Golden State?","California"),
 ("How many states are in the United States?","50","fifty"),
 ("What is NATO short for?","North Atlantic Treaty Organization"),
 ("What year did the French Revolution begin?","1789"),
 ("What year did the American Declaration of Independence get signed?","1776"),
 ("What company was founded by Steve Jobs and Steve Wozniak?","Apple"),
 ("What company was founded by Bill Gates?","Microsoft"),
 ("What company was founded by Jeff Bezos?","Amazon"),
 ("Who is the founder of Tesla and SpaceX?","Elon Musk","Musk"),
 ("What is the world's largest search engine?","Google"),
 ("What programming language is named after a snake?","Python"),
 ("What does CPU stand for?","central processing unit"),
 ("What does HTML stand for?","hypertext markup language"),
 ("What does WWW stand for?","world wide web"),
 ("What does GPS stand for?","global positioning system"),
 ("What year was the first iPhone released?","2007"),
 ("What company created the Windows operating system?","Microsoft"),
 ("What was the first man-made satellite launched into space?","Sputnik"),
 ("What year was Sputnik launched?","1957"),
 ("What space agency put the first man on the moon?","NASA"),
 ("What is the name of NASA's most famous space telescope?","Hubble"),
 ("How many teeth does an adult human typically have?","32","thirty-two"),
 ("What is the largest muscle in the human body?","gluteus maximus"),
 ("What vitamin do you get primarily from sunlight?","vitamin D"),
 ("What do you call a doctor who treats teeth?","dentist"),
 ("What do you call a doctor who treats animals?","veterinarian","vet"),
 ("What do you call a doctor who treats the heart?","cardiologist"),
 ("What is the longest wall in the world?","Great Wall","Great Wall of China"),
 ("What canal connects the Atlantic and Pacific oceans?","Panama","Panama Canal"),
 ("What canal connects the Mediterranean and Red seas?","Suez","Suez Canal"),
 ("What is the largest island in the world?","Greenland"),
 ("What sea separates Europe and Africa?","Mediterranean"),
 ("What strait separates Asia and North America?","Bering","Bering Strait"),
 ("What is the most populous city in the world?","Tokyo"),
 ("What organization is headquartered in New York and promotes world peace?","United Nations","UN"),
 ("What document begins with 'We the People'?","the Constitution"),
 ("What war was fought between the North and South in the US?","Civil War"),
 ("In what city was John F. Kennedy assassinated?","Dallas"),
 ("What is the best-selling video game console of all time?","PlayStation 2","PS2"),
 ("What social media platform was founded by Mark Zuckerberg?","Facebook"),
]
for q, *ans in extra_facts:
    add_factual(q, *ans)

# =====================================================================
# EXPLAIN / WHY (~60%, target ~600) -- topic + required concepts,
# each topic phrased 4 ways to build genuine scale without pure repetition
# =====================================================================
topics = [
 ("leaves changing color in autumn", ["chlorophyll","sunlight"]),
 ("the sky being blue", ["scattering","wavelength"]),
 ("the seasons changing", ["axis","tilt"]),
 ("rainbows forming", ["light","refraction"]),
 ("the tides", ["moon","gravity"]),
 ("volcanoes erupting", ["magma","pressure"]),
 ("earthquakes happening", ["plates","fault"]),
 ("thunder and lightning", ["electric","charge"]),
 ("clouds forming", ["water vapor","condensation"]),
 ("snow forming", ["ice crystals","temperature"]),
 ("day and night", ["rotation","Earth"]),
 ("eclipses happening", ["shadow","alignment"]),
 ("stars twinkling", ["atmosphere","light"]),
 ("the moon having phases", ["orbit","sunlight"]),
 ("hot air balloons rising", ["density","air"]),
 ("airplanes staying in the air", ["lift","wing"]),
 ("boats floating", ["buoyancy","density"]),
 ("magnets attracting metal", ["magnetic field","poles"]),
 ("mirrors reflecting light", ["reflection","surface"]),
 ("ice floating on water", ["density","expand"]),
 ("bread rising when baked", ["yeast","gas"]),
 ("milk turning sour", ["bacteria","spoil"]),
 ("fruit ripening", ["ethylene","enzyme"]),
 ("plants needing sunlight", ["photosynthesis","energy"]),
 ("bees making honey", ["nectar","enzyme"]),
 ("animals hibernating in winter", ["energy","food"]),
 ("some animals migrating", ["season","food"]),
 ("chameleons changing color", ["camouflage","cells"]),
 ("humans needing sleep", ["brain","rest"]),
 ("muscles getting sore after exercise", ["lactic acid","fiber"]),
 ("the heart beating", ["electrical","muscle"]),
 ("people getting goosebumps", ["muscle","hair"]),
 ("wounds forming scabs", ["clotting","platelets"]),
 ("vaccines working", ["immune system","antibodies"]),
 ("fevers happening", ["immune","infection"]),
 ("antibiotics fighting infections", ["bacteria","cell wall"]),
 ("caffeine keeping people awake", ["adenosine","receptor"]),
 ("people getting sunburned", ["UV","skin"]),
 ("teeth getting cavities", ["bacteria","enamel"]),
 ("hair turning gray with age", ["melanin","pigment"]),
 ("computers overheating", ["processor","heat"]),
 ("batteries losing charge over time", ["chemical","reaction"]),
 ("wifi signals getting weaker with distance", ["signal","interference"]),
 ("phones getting warm while charging", ["current","resistance"]),
 ("touchscreens responding to fingers", ["capacitive","electric"]),
 ("GPS being able to find your location", ["satellite","signal"]),
 ("rust forming on metal", ["oxygen","iron"]),
 ("glass being transparent", ["structure","light"]),
 ("sound traveling faster in water than air", ["density","medium"]),
 ("echoes happening", ["sound wave","reflection"]),
 ("the ocean being salty", ["minerals","rivers"]),
 ("deserts being dry", ["rainfall","climate"]),
 ("glaciers moving", ["gravity","ice"]),
 ("rivers forming deltas", ["sediment","current"]),
 ("coral reefs being colorful", ["algae","symbiosis"]),
 ("the ozone layer protecting Earth", ["ozone","UV"]),
 ("greenhouse gases causing warming", ["heat","atmosphere"]),
 ("compound interest making money grow faster over time", ["interest","principal"]),
 ("inflation making prices rise", ["money supply","demand"]),
 ("supply and demand affecting prices", ["supply","demand"]),
 ("stock prices going up and down", ["buyers","sellers"]),
 ("time zones existing", ["rotation","longitude"]),
 ("leap years existing", ["orbit","calendar"]),
 ("the calendar having 12 months", ["moon","cycle"]),
 ("some countries driving on the left", ["history","tradition"]),
 ("languages evolving over time", ["usage","generations"]),
 ("accents developing in different regions", ["isolation","pronunciation"]),
 ("music can make people feel emotions", ["brain","rhythm"]),
 ("optical illusions tricking the brain", ["perception","brain"]),
 ("deja vu happening", ["memory","brain"]),
 ("people forgetting dreams quickly", ["memory","sleep"]),
 ("yawning being contagious", ["brain","empathy"]),
 ("babies not remembering being babies", ["brain","memory"]),
 ("placebo effects working", ["brain","expectation"]),
 ("addiction being hard to overcome", ["dopamine","brain"]),
 ("stress affecting the body", ["cortisol","hormone"]),
 ("exercise improving mood", ["endorphins","brain"]),
 ("fasting affecting the body", ["metabolism","energy"]),
 ("the internet working across the world", ["network","data"]),
 ("passwords needing to be encrypted", ["encryption","security"]),
 ("solar panels generating electricity", ["sunlight","cells"]),
 ("wind turbines generating electricity", ["wind","generator"]),
 ("nuclear power plants generating energy", ["reaction","heat"]),
 ("electric cars needing large batteries", ["energy","storage"]),
 ("3D printers building objects layer by layer", ["material","layer"]),
 ("recycling helping the environment", ["waste","resources"]),
 ("plastic taking so long to decompose", ["polymer","chemical"]),
 ("bridges being built with trusses", ["structure","support"]),
 ("skyscrapers not falling over in wind", ["structure","sway"]),
 ("black holes existing", ["gravity","mass"]),
 ("the universe expanding", ["space","galaxies"]),
 ("astronauts float in space", ["gravity","orbit"]),
 ("rockets need so much fuel", ["thrust","mass"]),
 ("the Great Wall of China was built", ["defense","border"]),
 ("ancient Egyptians built pyramids", ["labor","stone"]),
 ("democracy developed in ancient Greece", ["citizens","voting"]),
 ("the Roman Empire fell", ["invasion","economy"]),
 ("the printing press changed history", ["books","literacy"]),
 ("the Industrial Revolution happened", ["machines","factories"]),
 ("World War I started", ["alliances","assassination"]),
 ("the Great Depression happened", ["stock market","banks"]),
 ("the Cold War happened", ["ideology","nuclear"]),
 ("colonization affected indigenous peoples", ["land","culture"]),
 ("spicy food feels hot", ["capsaicin","receptors"]),
 ("onions make you cry", ["enzyme","gas"]),
 ("popcorn pops", ["moisture","pressure"]),
 ("bread goes stale", ["starch","moisture"]),
 ("coffee tastes bitter", ["compounds","roast"]),
 ("chocolate melts in your mouth", ["fat","temperature"]),
 ("carbonated drinks fizz", ["carbon dioxide","pressure"]),
 ("fruit turns brown after being cut", ["oxidation","enzyme"]),
 ("cooking meat changes its color", ["protein","heat"]),
 ("salt preserves food", ["moisture","bacteria"]),
 ("fermentation is used to make foods like yogurt", ["bacteria","culture"]),
 ("some foods spoil faster than others", ["moisture","bacteria"]),
 ("freezing food preserves it", ["bacteria","temperature"]),
 ("humans dream while sleeping", ["brain","REM"]),
 ("people get jet lag", ["circadian","time zone"]),
 ("some people are left-handed", ["brain","genetics"]),
 ("twins can look identical", ["genetics","embryo"]),
 ("blood types are different between people", ["antigens","genetics"]),
 ("allergies happen", ["immune system","allergen"]),
 ("scars form on skin", ["collagen","healing"]),
 ("bruises change color as they heal", ["blood","hemoglobin"]),
 ("people get hiccups", ["diaphragm","nerve"]),
 ("babies are born unable to walk", ["muscles","brain"]),
 ("bones heal after breaking", ["cells","calcium"]),
 ("some medicines need to be taken with food", ["absorption","stomach"]),
 ("anesthesia makes you unconscious", ["nervous system","brain"]),
 ("radio waves can carry sound", ["frequency","signal"]),
 ("microwaves heat food", ["radiation","molecules"]),
 ("lasers can cut materials", ["light","energy"]),
 ("fiber optic cables carry data so fast", ["light","signal"]),
 ("solar eclipses are rare", ["orbit","alignment"]),
 ("some metals conduct electricity better than others", ["electrons","structure"]),
 ("diamonds are so hard", ["carbon","structure"]),
 ("helium makes your voice sound funny", ["density","sound"]),
 ("dry ice creates fog", ["carbon dioxide","sublimation"]),
 ("soap helps clean things", ["molecules","grease"]),
 ("oil and water dont mix", ["polarity","molecules"]),
 ("some objects sink while others float", ["density","buoyancy"]),
 ("a compass points north", ["magnetic field","poles"]),
 ("shadows change length during the day", ["sun","angle"]),
 ("some clouds bringing rain and others not", ["moisture","altitude"]),
 ("hurricanes form over oceans", ["warm water","pressure"]),
 ("deserts get cold at night", ["humidity","heat"]),
 ("mountains are colder than valleys", ["altitude","pressure"]),
 ("the equator is hotter than the poles", ["sunlight","angle"]),
 ("fish can breathe underwater", ["gills","oxygen"]),
 ("birds can fly", ["wings","bones"]),
 ("some animals are venomous", ["toxin","defense"]),
 ("spiders can walk on walls", ["hair","adhesion"]),
 ("cats can see in the dark", ["eyes","retina"]),
 ("dogs have a strong sense of smell", ["nose","receptors"]),
 ("some plants are carnivorous", ["nutrients","soil"]),
 ("cacti can survive in the desert", ["water","adaptation"]),
 ("trees lose their leaves in winter", ["energy","cold"]),
 ("seeds need water to germinate", ["water","enzyme"]),
 ("bamboo grows so fast", ["cells","growth"]),
 ("mushrooms grow overnight", ["spores","moisture"]),
]

# Only templates that are grammatically robust with gerund-phrase topics
# (e.g. "leaves changing color", "eclipses happening") are used. Templates
# like "Why does {t}?" were tried first and produced broken grammar
# ("Why does some clouds bring rain?") because they need a finite-clause
# object, not a noun phrase -- caught by inspection before shipping and
# replaced with templates that take a noun phrase correctly.
ALL_TEMPLATES = [
    "What causes {t}?",
    "Can you explain what causes {t}?",
    "Explain how {t} works.",
    "What is the reason behind {t}?",
]
for topic, concepts in topics:
    for tmpl in ALL_TEMPLATES:
        q = tmpl.format(t=topic)
        q = q[0].upper() + q[1:]
        add_explain(q, *concepts)

random.shuffle(qa)
out = pathlib.Path(__file__).parent.parent.parent / "data" / "qa_v2.jsonl"
out.parent.mkdir(exist_ok=True)
with open(out, "w") as f:
    for i, ex in enumerate(qa):
        ex["id"] = f"qav2_{i:04d}"
        f.write(json.dumps(ex) + "\n")

n_factual = sum(1 for e in qa if e["type"] == "factual")
n_explain = sum(1 for e in qa if e["type"] == "explain")
print(f"wrote {len(qa)} questions to {out}")
print(f"  factual: {n_factual} ({n_factual/len(qa)*100:.0f}%)")
print(f"  explain: {n_explain} ({n_explain/len(qa)*100:.0f}%)")
